PAGINATED_BY = 100

COUPON_MAX_USAGE = 200


LATEST_QUERYSET_LIMIT = 10

DECIMAL_PLACES = 2
DECIMAL_MAX_DIGITS = 10
PRODUCT_NUMBER_LENGTH = 6

COMMISSION_DEFAULT = 0.03
COMMISSION_MAX_DIGITS = 7
COMMISSION_DECIMAL_PLACES = 5

AJAX_CONTENT_TYPE = "application/json"