PAGINATED_BY = 100

COUPON_MAX_USAGE = 200


LATEST_QUERYSET_LIMIT = 10
RECENT_LIMIT = 8

DECIMAL_PLACES = 2
MAX_DIGITS = 10
PRODUCT_NUMBER_LENGTH = 6

COMMISSION_DEFAULT = 0.03
COMMISSION_MAX_DIGITS = 7
COMMISSION_DECIMAL_PLACES = 5

AJAX_CONTENT_TYPE = "application/json"

SELLER_GROUP = "Sellers"
PARTNER_GROUP = "Partners"
SUPERVISOR_GROUP = "Supervisor"
OPERATOR_GROUP = "Operators"
API_USER_GROUP = "API-USERS"

BASIC_PARTNER_GROUP = "BASIC"
SILVER_PARTNER_GROUP = "SILVER"
GOLD_PARTNER_GROUP = "GOLD"
PLATINUM_PARTNER_GROUP = "PLATINUM"