
from django.utils.translation import gettext_lazy as _


UI_PAGE_NOT_ALLOWED = _('You are allowed to access this page')
UI_RECHARGE_LIST_TITLE = _('Recharges')
UI_RECHARGE_TITLE = _('Recharge')
UI_VOUCHER_LIST_TITLE = _('Vouchers')
UI_VOUCHER_TITLE = _('Voucher')
UI_SOLD_VOUCHER_LIST_TITLE = _('Sold Vouchers')
UI_SOLD_VOUCHER_TITLE = _('Sold Voucher')
UI_USED_VOUCHER_LIST_TITLE = _('Used Vouchers')
UI_USED_VOUCHER_TITLE = _('Used Voucher')
UI_BALANCE_RECHARGE_TITLE = _('Balance Recharge')
UI_PAYMENT_LIST_TITLE = _('Payments')
UI_PAYMENT_TITLE = _('Payment')
UI_TRANSFER_LIST_TITLE = _('Transfers')
UI_TRANSFER_TITLE = _('Transfer')
UI_SERVICES_LIST_TITLE = _('Services')
UI_SERVICE_TITLE = _('Service')
UI_CATEGORY_LIST_TITLE = _('Categories')
UI_CATEGORY_TITLE = _('Category')
UI_VOUCHER_GENERATE_TITLE = _('Generate Voucher')
UI_POLICY_LIST_TITLE = _('Policies')
UI_POLICY_TITLE = _('Policy')
UI_POLICY_GROUP_LIST_TITLE = _('Policy Groups')
UI_POLICY_GROUP_TITLE = _('Policy Group')
UI_SERVICE_PARTNER_LIST_TITLE = _('Partners')
UI_SERVICE_PARTNER_TITLE  = _('Partner')
UI_GROUP_LIST_TITLE = _('Groups')
UI_GROUP_TITLE = _('Group')
UI_USER_LIST_TITLE = _('Users')
UI_USER_TITLE = _('User')
UI_SELLER_LIST_TITLE = _('Sellers')
UI_SELLER_TITLE = _('Seller')
UI_TOKEN_GENERATE_TITLE = _('Generate Token')

UI_REPORT_TITLE = _('Reports')