
from django.utils.translation import gettext_lazy as _


UI_PAGE_NOT_ALLOWED = _('You are not allowed to access this page')
UI_RECHARGE_LIST_TITLE = _('Recharges')
UI_RECHARGE_TITLE = _('Recharge')
UI_VOUCHER_LIST_TITLE = _('Vouchers')
UI_VOUCHER_TITLE = _('Voucher')
UI_SOLD_VOUCHER_LIST_TITLE = _('Sold Vouchers')
UI_SOLD_VOUCHER_TITLE = _('Sold Voucher')
UI_USED_VOUCHER_LIST_TITLE = _('Used Vouchers')
UI_USED_VOUCHER_TITLE = _('Used Voucher')
UI_BALANCE_RECHARGE_TITLE = _('Balance Recharge')
UI_PAYMENT_LIST_TITLE = _('Payments')
UI_PAYMENT_TITLE = _('Payment')
UI_PAYMENT_REQUEST_TITLE = _('Payment Request')
UI_PAYMENT_REQUEST_LIST_TITLE = _('Payment Requests')
UI_TRANSFER_LIST_TITLE = _('Transfers')
UI_TRANSFER_TITLE = _('Transfer')
UI_SERVICE_LIST_TITLE = _('Services')
UI_SERVICE_TITLE = _('Service')
UI_CATEGORY_LIST_TITLE = _('Categories')
UI_CATEGORY_TITLE = _('Category')
UI_CATEGORY_UPDATE_TITLE = _('Category Update')
UI_CATEGORY_CREATE_TITLE = _('New Category')
UI_VOUCHER_GENERATE_TITLE = _('Generate Voucher')
UI_POLICY_LIST_TITLE = _('Policies')
UI_POLICY_TITLE = _('Policy')
UI_POLICY_UPDATE_TITLE = _('Policy Update')
UI_POLICY_CREATE_TITLE = _('New Policy')
UI_POLICY_GROUP_LIST_TITLE = _('Policy Groups')
UI_POLICY_GROUP_TITLE = _('Policy Group')
UI_POLICY_GROUP_UPDATE_TITLE = _('Policy Group Update')
UI_POLICY_GROUP_CREATE_TITLE = _('New Policy Group')
UI_SERVICE_PARTNER_LIST_TITLE = _('Partner Services')
UI_SERVICE_PARTNER_TITLE  = _('Partner Service')
UI_SERVICE_PARTNER_UPDATE_TITLE  = _('Partner Service Update')
UI_SERVICE_PARTNER_CREATE_TITLE  = _('New Partner Service')
UI_GROUP_LIST_TITLE = _('Groups')
UI_GROUP_TITLE = _('Group')
UI_GROUP_UPDATE_TITLE = _('Group Update')
UI_GROUP_CREATE_TITLE = _('New Group')
UI_USER_LIST_TITLE = _('Users')
UI_USER_TITLE = _('User')
UI_USER_UPDATE_TITLE = _('User Update')
UI_USER_CREATE_TITLE = _('New User')
UI_SELLER_LIST_TITLE = _('Sellers')
UI_SELLER_TITLE = _('Seller')
UI_SELLER_UPDATE_TITLE = _('Seller Update')
UI_SELLER_CREATE_TITLE = _('New Seller')
UI_TOKEN_GENERATE_TITLE = _('Generate Token')
UI_TOKEN_LIST_TITLE = _('Tokens')
UI_TOKEN_TITLE = _('Token')
UI_REPORT_TITLE = _('Reports')
UI_DASHBOARD_TITLE = _('Dashboard')


# PAYMENTS
CASHOUT_WITHDRAW_STR = _('WITHDRAW')
CASHOUT_CASHOUT_STR = _('CASHOUT')
CASHOUT_CASHIN_STR = _('CASHIN')

BALANCE_ACTIVITY_TYPE_STR  = _('ACTIVITY TYPE')
BALANCE_RECHARGE_STR = _('RECHARGE')
BALANCE_PAYMENT_STR  = _('PAYMENT')
BALANCE_TRANSFER_STR = _('TRANSFER')
BALANCE_REFUND_STR = _('REFUND')
BALANCE_CASHOUT_STR = CASHOUT_CASHOUT_STR
BALANCE_CASHIN_STR = CASHOUT_CASHIN_STR
BALANCE_WITHDRAW_STR = CASHOUT_WITHDRAW_STR


UI_CASHOUT_USER_AGENT_INVALID = _('User and Agent should not be the same')
UI_CASHOUT_USER_INSUFFICIENT_BALANCE  = _('User has no sufficient balance')
UI_CASHOUT_AGENT_INVALID  = _('agent does not belongs to the group of Agents')
UI_CASHOUT_USER_INVALID  = _('user must not be an agent')
UI_INVALID_USER_REQUEST = _('Invalid user request')
UI_POLICY_UPDATED = _('POLICY updated')
UI_POLICY_ALREADY_MEMBERS = _('User is already a member of the Group')
UI_NEW_PAYMENTS_RECEIVED = _('New Payments')
UI_INVALID_DATE_REPORT = _('Invalid Date')
UI_INVALID_REQUEST = _('Invalid Request')