from django.utils.translation import gettext as _

CASHOUT_WITHDRAW_STR = _('WITHDRAW')
CASHOUT_CASHOUT_STR = _('CASHOUT')
CASHOUT_CASHIN_STR = _('CASHING')

BALANCE_ACTIVITY_TYPE_STR  = _('ACTIVITY TYPE')
BALANCE_RECHARGE_STR = _('RECHARGE')
BALANCE_PAYMENT_STR  = _('PAYMENT')
BALANCE_SERVICE_STR  = _('SERVICE')
BALANCE_TRANSFER_STR = _('TRANSFER')
BALANCE_REFUND_STR = _('REFUND')
BALANCE_CASHOUT_STR = CASHOUT_CASHOUT_STR
BALANCE_CASHIN_STR = CASHOUT_CASHIN_STR
BALANCE_WITHDRAW_STR = CASHOUT_WITHDRAW_STR


UI_CASHOUT_USER_AGENT_INVALID = _('Invalid cashout data. User and Agent should not be the same')
UI_CASHOUT_USER_INSUFFICIENT_BALANCE  = _('User has no suffient balance')
UI_CASHOUT_AGENT_INVALID  = _('agent does not belongs to the group of Agents')
UI_CASHOUT_USER_INVALID  = _('user must not be an agent')
UI_INVALID_USER_REQUEST = _('Invalid user request')