from django.utils.translation import gettext as _

BALANCE_ACTIVITY_TYPE_STR  = _('ACTIVITY TYPE')
BALANCE_RECHARGE_STR = _('RECHARGE')
BALANCE_PAYMENT_STR  = _('PAYMENT')
BALANCE_TRANSFER_STR = _('TRANSFER')
BALANCE_REFUND_STR = _('REFUND')