from django.utils.translation import gettext as _

CASHOUT_WITHDRAW_STR = _('WITHDRAW')
CASHOUT_CASHOUT_STR = _('CASHOUT')
CASHOUT_CASHIN_STR = _('CASHING')

BALANCE_ACTIVITY_TYPE_STR  = _('ACTIVITY TYPE')
BALANCE_RECHARGE_STR = _('RECHARGE')
BALANCE_PAYMENT_STR  = _('PAYMENT')
BALANCE_SERVICE_STR  = _('SERVICE')
BALANCE_TRANSFER_STR = _('TRANSFER')
BALANCE_REFUND_STR = _('REFUND')
BALANCE_CASHOUT_STR = CASHOUT_CASHOUT_STR
BALANCE_CASHIN_STR = CASHOUT_CASHIN_STR
BALANCE_WITHDRAW_STR = CASHOUT_WITHDRAW_STR


UI_CASHOUT_USER_AGENT_INVALID = _('Invalid cashout data. User and Agent should not be the same')
UI_CASHOUT_USER_INSUFFICIENT_BALANCE  = _('User has no suffient balance')
UI_CASHOUT_AGENT_INVALID  = _('agent does not belongs to the group of Agents')
UI_CASHOUT_USER_INVALID  = _('user must not be an agent')
UI_INVALID_USER_REQUEST = _('Invalid user request')

UI_NO_TRANSACTIONS_AVAILABLE = _('There is no transactions yet')
UI_NO_SERVICE_AVAILABLE = _('No service available')

# CATEGORIES STRINGS
UI_CATEGORY_EDUCATION = _('Education')
UI_CATEGORY_ELECTRICITY = _('Electricity')
UI_CATEGORY_HEALTH = _('Health')
UI_CATEGORY_WATER = _('Water')
UI_CATEGORY_TRAVEL = _('Travel')
UI_CATEGORY_ENTERTAINMENT = _('Entertainment')
UI_CATEGORY_BUSINESS = _('Business')
UI_CATEGORY_ONLINE_SHOPPING = _('Online Shopping')

# TRANSACTIONS
UI_MAKE_TRANSFER_LABEL = _('Send money')
UI_MAKE_PAYMENT_LABEL = _('Make payment')
UI_MAKE_RECHARGE_LABEL = _('Recharge')
UI_CURRENT_BALANCE_LABEL = _('Current balance')
UI_STATISTICS_LABEL = _('Statistics')

UI_TRANSACTIONS_LABEL = _('Transactions')
UI_AVAILABLE_SERVICES_LABEL = _('Available Services')
UI_CATEGORIES_LABEL = _('Categories')
UI_TRANSACTIONS_VERIFICATION_LABEL = _('Transactions verification')
UI_RECIPIENT_LABEL = _('Recipient')
UI_SELLER_LABEL = _('Seller')
UI_AMOUNT_LABEL = _('Amount')
UI_DESCRIPTION_LABEL = _('Description')
UI_VOUCHER_CODE_LABLE = _('Voucher Code')
